name: YouTube Video Update Cron Job

on:
    # schedule:
    #     - cron: "*/10 * * * *" # Runs every 10 minutes
    workflow_dispatch:

jobs:
    update-video:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js v22.13.0
              uses: actions/setup-node@v2
              with:
                  node-version: "22.13.0"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies with pnpm
              run: pnpm install

            - name: Run YouTube Update Script
              env:
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  VIDEO_ID: ${{ secrets.VIDEO_ID }}
              run: pnpm run update:video
